services:
  - type: web
    name: bathtub-app
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    build:
      publishPath: ./dist
      command: npm run build
