services:
  - type: web
    name: bathtub-app
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    previews:
      generation: automatic # Enable service previews
    buildFilter:
      paths:
        - src/**/*.js
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /old
        destination: /new
      - type: rewrite
        source: /a/*
        destination: /a
